[package]
name = "bucket-cleanup"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-sdk-s3 = "1.65.0"
indicatif = "0.17.9"
tokio = { version = "1.42.0", features = ["full"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
